### ISSUE TITLE
Possible to delete coupons using this library?

### ISSUE THREAD

**Issue by adamq-q** [MartinAmps/Shopify-Private-APIs#3]
Is it at all *possible* to delete coupons dynamically in Shopify?

**Comment by MartinAmps** [comment]
So it was -- Shopify has since created a plus API which has these capabilities: https://docs.shopify.com/api/discounts#destroy

The authentication method is different so I'm not sure if you'll be able to make it work with this library anymore :( the README.md has an example of listing all coupons which gets you half way there. I just committed support for the DELETE method, you could try doing something like:

    $api->doRequest('DELETE', "discounts/{$coupon->id}.json", []);

Let me know if it works!

**Comment by adamq-q** [comment]
Thanks! I was trying something similar to your new commit. 

Then, I get `"Invalid API key or access token (unrecognized login or wrong password)"`

But by adding the same tokens as the POST to the DELETE method I'm able to get to a new error:
curl_errno returning Error 47: `Maximum (20) redirects followed` :fearful: 

```php
    CURLOPT_CUSTOMREQUEST => 'DELETE',
    CURLOPT_URL => $url,
    CURLOPT_HTTPHEADER => [
        'X-Shopify-Api-Features: pagination-headers',
        'X-CSRF-Token: ' . $this->_token,
        'X-Requested-With: XMLHttpRequest',
        'Content-Type: application/json',
        'Accept: application/json'
    ]
```

By the way, this library is a lifesaver. It still works just fine for creating new coupons.

**Comment by MartinAmps** [comment]
Hmm - try adding a debug step in to see where it’s redirecting you. I can take a look at this tonight, but no promises!

**Comment by adamq-q** [comment]
Thanks again :D I'm trying to follow the redirects with something like this http://zzz.rezo.net/HowTo-Expand-Short-URLs.html but not getting anywhere. Will keep poking at it and let you know if I figure out what's going on.

**Comment by MartinAmps** [comment]
Did you get this working? :)
